backend:
  name: github
  repo: fedeneri/laboratorio-politico-ravanusella
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pagine"
    label: "Pagine del sito"
    files:
      - name: "index"
        label: "Homepage"
        file: "index.html"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Contenuto", name: "body", widget: "markdown" }
